import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Modal from "@/components/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  leftmenu,
  rightmenu,
  children,
}: Readonly<{
  leftmenu: React.ReactNode;
  rightmenu: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative flex">
          <Modal />
          {leftmenu}
          {children}
          {rightmenu}
        </main>
      </body>
    </html>
  );
}
